#!/bin/bash

compilation ()
{
    pdflatex $1;
    pdflatex $1;
    pdflatex $1;
}

suppression ()
{
    rm $1.log
    rm $1.aux
    rm $1.toc
    rm $1.out
}

usage ()
{
    echo "Usage :"
    echo "Sans arguments : Fichier .tex"
    echo "-b : Compile avec la bibliothèque"
}

open_pdf()
{
    str=${1::-4}
    echo "Do you want to open $str.pdf?";
    select yn in "Yes" "No";
    do
	case $yn in
	    Yes ) evince $str.pdf & break;;
	    No  ) exit;;
	esac
    done
}


###Compilation###

# Sans paramètres
if (( $# == 1 )); then
    compilation $1;
    suppression $str;
# Avec Bibliothèque
elif (( $# == 2 )); then
    if [[ "$1" == "-b" ]]; then
	str=${2::-4}
	echo "$str"
	compilation $str.tex;#on peut le remplacer par pdflatex si on veut gagner en rapiditer(inutile de le faire 3 fois avec la fonction compilation)
	bibtex $str.aux
	compilation $str.tex;
	suppression $str;
        rm $str.bbl
	rm $str.blg
    else
	usage;
    fi
fi

###Affichage###

if (( $# == 1 )); then
    open_pdf $1;
elif (( $# == 2 )); then 
    open_pdf $2;
fi
