#!/bin/bash

t=('0.01' '0.025' '0.05' '0.1' '0.15' '0.2' '0.25' '0.3' '0.35' '0.4' '0.45')
feh -xFY --auto-zoom -D${t[$(< /dev/urandom tr -dc 0-9 | head -c1)]} /net/cremi/gchupin/espaces/travail/2k/MPe*
